import { WorcestershiresauceAnimation } from "./animations/WorcestershiresauceAnimation";
import { TabascoAnimation } from "./animations/TabascoAnimation";
import { SambalAnimation } from "./animations/SambalAnimation";
import { KipAnimation } from "./animations/KipAnimation";
import { PaprikapoederAnimation } from "./animations/PaprikapoederAnimation";
import { EggslutAnimation } from "./animations/EggslutAnimation";
import { Wijn1Animation } from "./animations/Wijn1Animation";
import { Wijn2Animation } from "./animations/Wijn2Animation";
import { Lijn1Animation } from "./animations/Lijn1Animation";
import { Lijn2Animation } from "./animations/Lijn2Animation";
import { FotolijstjeAnimation } from "./animations/FotolijstjeAnimation";
import { Lijn3Animation } from "./animations/Lijn3Animation";
import { Lijn4Animation } from "./animations/Lijn4Animation";
import { CupcakeAnimation } from "./animations/CupcakeAnimation";
import { Cactus1Animation } from "./animations/Cactus1Animation";
import { Cactus2Animation } from "./animations/Cactus2Animation";
import { Cactus3Animation } from "./animations/Cactus3Animation";
import { KoffiepotjeAnimation } from "./animations/KoffiepotjeAnimation";
import { Lijn5Animation } from "./animations/Lijn5Animation";
import { Lijn6Animation } from "./animations/Lijn6Animation";
import { LepelAnimation } from "./animations/LepelAnimation";
import { OvenwantAnimation } from "./animations/OvenwantAnimation";
import { LijstjecoronaAnimation } from "./animations/LijstjecoronaAnimation";
import { LijstjezoetzuresausAnimation } from "./animations/LijstjezoetzuresausAnimation";

export { TabascoAnimation, WorcestershiresauceAnimation, SambalAnimation, KipAnimation, PaprikapoederAnimation , EggslutAnimation, Wijn1Animation, Wijn2Animation, Lijn1Animation, Lijn2Animation, FotolijstjeAnimation, Lijn3Animation, Lijn4Animation, CupcakeAnimation, Cactus1Animation, Cactus2Animation, Cactus3Animation, KoffiepotjeAnimation, Lijn5Animation, Lijn6Animation, LepelAnimation, OvenwantAnimation, LijstjecoronaAnimation, LijstjezoetzuresausAnimation };
